var GServiceType = {
    'idwzryhw':{
        'gameId':1181,
        'id':1000507,
        'login':'garena',
        'api':'https://external.mrms.garena.co.id',
    },
    'twwzryhw':{
        'gameId':1130,
        'id':100050,
        'login':'garena',
        'api':'https://external.mrms.garena.tw'
    },
    'thawzryhw':{
        'gameId':1138,
        'id':100054,
        'login':'garena',
        'api':'https://external.mrms.garena.in.th'
    },
    'vnwzryhw':{
        'gameId':1137,
        'id':100055,
        'login':'garena',
        'api':'https://external.mrms.garena.vn'
    },
    'nawzryhw':{
        'gameId':1134,
        'id':1134,
        'login':'facebook',
        'api':'https://mrms.na.ngame.proximabeta.com'
    },
    'sawzryhw':{
        'gameId':1136,
        'id':1136,
        'login':'facebook',
        'api':'https://mrms.sa.ngame.proximabeta.com'
    }
};